name: smart_bus_passenger_ui
description: "Smart Bus Accident & Passenger Health Monitoring System with Edge Intelligence and Gemini AI."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  fl_chart: ^0.70.2
  csv: ^6.0.0
  http: ^1.3.0
  flutter_blue_plus: ^1.32.0
  file_picker: ^8.0.0
  supabase_flutter: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/bus_sensor_data.csv
    - assets/data/passenger_health_data.csv
